### ISSUE TITLE
Membergroup export in usync?

### ISSUE THREAD

**Issue by markwemekamp** [KevinJump/uSync3.0#113]
For a project I'm currently doing it would be nice to have a membergroup export in usync or usync content.
 
Is this somehting you've thought about and decided not to implement for good reasons or would this be a viable feature for the future?

**Comment by KevinJump** [comment]
Hi Mark, 

For me its purely a time thing - I don't think there are to many reasons why it shouldn't be doable - i just haven't had the extra time lately needed to write it 😞 

Someone was talking about this a few weeks back https://our.umbraco.org/projects/developer-tools/usync/usync/82167-implementing-isynchandler-for-members but i am not sure if they did anything with it. 

I do think its something that might be worth doing but i would have to carve some time out at somepoint. 

If it's something you really need i could be bribed (with money - so not really bribed but paid 😄  )

**Comment by markwemekamp** [comment]
Hey Kevin,
Thanks for the feedback, I'll keep an eye on the our thread :)

I'll ask my employer if they're willing to pay for this feature. Maybe I'll even take shot at implementing it myself if time allows it.

**Comment by KevinJump** [comment]
Hi 

I recently received a Pull Request with this and other handlers in it https://github.com/KevinJump/uSync/pull/129

I have merged this into the next minor release branch , so once it's been tested a bit it will be in the core of usync. https://github.com/KevinJump/uSync/tree/uSync_3.4
