### ISSUE TITLE
Content Export Issue

### ISSUE THREAD

**Issue by duncanl-living** [KevinJump/uSync3.0#116]
Hi, I'm having trouble exporting some of my content and the content that failed to export comes up highlighted orange on the "Export Processed" list.

Also in my trace log I've been seeing this:

[P16972/D3/T154] WARN  Jumoo.uSync.Content.ContentHandler - Error saving Content: System.NullReferenceException: Object reference not set to an instance of an object.
   at Jumoo.uSync.Core.Mappers.GridMapper.ProcessGridValues(String content, Boolean import)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.GetExportIds(PropertyType propType, XElement value)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.SerializeBase(IContentBase item, String contentTypeAlias)
   at Jumoo.uSync.Core.Serializers.ContentSerializer.SerializeCore(IContent item)
   at Jumoo.uSync.Content.ContentHandler.ExportItem(IContent item, String path, String rootFolder)

Please can you help identify what the issue may be?

Thanks.

**Comment by KevinJump** [comment]
Hi, the content mapper is looking for IDs and it goes through the properties trying to find them.

looking at the code it's failing while looking in the grid. 

what type of controls are you using inside the grid ? - 
and do you know what content node is failing? 

if you can - go into the umbraco.config file in app_data, and find the grid values for the failing node - this will help me see what the value is before the content mapper trys to look into it.

**Comment by duncanl-living** [comment]
This is the failed node.

 <caseStudy id="2259" key="3738a0ba-e809-49f6-90fb-f3dcbbbcbc6e" parentID="2272" level="4" creatorID="0" sortOrder="21" createDate="2017-01-18T12:25:49" updateDate="2017-02-03T09:43:39" nodeName="AIA" urlName="aia" path="-1,1068,1095,2272,2259" isDoc="" nodeType="2252" creatorName="Duncan" writerName="Duncan" writerID="0" template="2257" nodeTypeAlias="caseStudy">
          <contentGrid><![CDATA[{
  "name": "1 column layout",
  "sections": [
    {
      "grid": 12,
      "rows": [
        {
          "label": "Headline",
          "name": "Headline",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": {
                    "macroAlias": "CaseStudyHeroSection",
                    "macroParamsDictionary": {
                      "image": "2470",
                      "heading": "Developing prestige cues for a premium audience in Asia"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The challenge",
                      "description": "Pan-Asian life insurance group AIA worked with us in partnership to develop a compelling new visual concept for its enhanced universal life product offering, Wealth Preserver 3. To target high net worth individuals, it was vital to reflect premium cues and build a brand image rich in prestige.",
                      "image": "2472"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The solution",
                      "description": "Working across our creative hubs in Hong Kong and London, we sought to develop a creative approach imbued with real meaning – and long term potential. Creating a truly elegant and thought-provoking visual treatment around the notion of the ‘Tree of Life’, we underscored the product’s ability to grow clients’ wealth and safeguard it for future generations, enabling a lasting legacy.",
                      "image": "2473"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "",
                      "description": "This creative treatment was then applied across a diverse suite of Wealth Preserver collateral and supporting communications in three languages: English, Traditional Chinese and Simplified Chinese.",
                      "image": "2474"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The result",
                      "description": "The sophisticated ‘Tree of Life’ has become the visual signature of Wealth Preserver across a diversity of channels and touchpoints in Asia, from product brochures and guides, to forms, leaflets, factsheets and digital templates.",
                      "image": "2475"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "focalPoint": {
                      "left": 0.5,
                      "top": 0.5
                    },
                    "id": 2471,
                    "image": "/media/1196/aia-1130x500-02.jpg",
                    "altText": "AIA 1130x500 02"
                  },
                  "editor": {
                    "alias": "media"
                  },
                  "active": false
                }
              ]
            }
          ],
          "hasConfig": false,
          "id": "f5a2d4d5-bca8-1a4e-5edd-cae3e937a182"
        }
      ]
    }
  ]
}]]></contentGrid>
          <pageTitle><![CDATA[AIA]]></pageTitle>
          <clientCaseStudyLogo><![CDATA[2410]]></clientCaseStudyLogo>
          <subHeading><![CDATA[AIA]]></subHeading>
          <caseStudyType><![CDATA[Digital,Brand]]></caseStudyType>
          <subDescription><![CDATA[Developing prestige cues for a premium audience in Asia]]></subDescription>
          <clientCaseStudyBackground><![CDATA[2408]]></clientCaseStudyBackground>
        </caseStudy>

**Comment by duncanl-living** [comment]
<caseStudy id="2259" key="3738a0ba-e809-49f6-90fb-f3dcbbbcbc6e" parentID="2272" level="4" creatorID="0" sortOrder="21" createDate="2017-01-18T12:25:49" updateDate="2017-02-03T09:43:39" nodeName="AIA" urlName="aia" path="-1,1068,1095,2272,2259" isDoc="" nodeType="2252" creatorName="Duncan" writerName="Duncan" writerID="0" template="2257" nodeTypeAlias="caseStudy">
          <contentGrid><![CDATA[{
  "name": "1 column layout",
  "sections": [
    {
      "grid": 12,
      "rows": [
        {
          "label": "Headline",
          "name": "Headline",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": {
                    "macroAlias": "CaseStudyHeroSection",
                    "macroParamsDictionary": {
                      "image": "2470",
                      "heading": "Developing prestige cues for a premium audience in Asia"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The challenge",
                      "description": "Pan-Asian life insurance group AIA worked with us in partnership to develop a compelling new visual concept for its enhanced universal life product offering, Wealth Preserver 3. To target high net worth individuals, it was vital to reflect premium cues and build a brand image rich in prestige.",
                      "image": "2472"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The solution",
                      "description": "Working across our creative hubs in Hong Kong and London, we sought to develop a creative approach imbued with real meaning – and long term potential. Creating a truly elegant and thought-provoking visual treatment around the notion of the ‘Tree of Life’, we underscored the product’s ability to grow clients’ wealth and safeguard it for future generations, enabling a lasting legacy.",
                      "image": "2473"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "",
                      "description": "This creative treatment was then applied across a diverse suite of Wealth Preserver collateral and supporting communications in three languages: English, Traditional Chinese and Simplified Chinese.",
                      "image": "2474"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "macroAlias": "CaseStudyContentSection",
                    "macroParamsDictionary": {
                      "heading": "The result",
                      "description": "The sophisticated ‘Tree of Life’ has become the visual signature of Wealth Preserver across a diversity of channels and touchpoints in Asia, from product brochures and guides, to forms, leaflets, factsheets and digital templates.",
                      "image": "2475"
                    }
                  },
                  "editor": {
                    "alias": "macro"
                  },
                  "active": false
                },
                {
                  "value": {
                    "focalPoint": {
                      "left": 0.5,
                      "top": 0.5
                    },
                    "id": 2471,
                    "image": "/media/1196/aia-1130x500-02.jpg",
                    "altText": "AIA 1130x500 02"
                  },
                  "editor": {
                    "alias": "media"
                  },
                  "active": false
                }
              ]
            }
          ],
          "hasConfig": false,
          "id": "f5a2d4d5-bca8-1a4e-5edd-cae3e937a182"
        }
      ]
    }
  ]
}]]></contentGrid>
          <pageTitle><![CDATA[AIA]]></pageTitle>
          <clientCaseStudyLogo><![CDATA[2410]]></clientCaseStudyLogo>
          <subHeading><![CDATA[AIA]]></subHeading>
          <caseStudyType><![CDATA[Digital,Brand]]></caseStudyType>
          <subDescription><![CDATA[Developing prestige cues for a premium audience in Asia]]></subDescription>
          <clientCaseStudyBackground><![CDATA[2408]]></clientCaseStudyBackground>
        </caseStudy>

**Comment by KevinJump** [comment]
thanks, i can prob work through that - but it will take a little time. 

if you turn debugging on in the log4net config 

  <logger name="Jumoo.uSync">
    <level value="Debug" />
  </logger>

you will get a lot more logging and it might help us pinpoint which of those values is failing.

**Comment by duncanl-living** [comment]
Hi Kevin, turned on debug and more or less the same error logged nothing more in particular.

 2017-02-03 12:03:19,466 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Serializers.ContentSerializer - Serialize Core: AIA
 2017-02-03 12:03:19,466 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Events - Mapping Content Export: Umbraco.Grid Custom
 2017-02-03 12:03:19,466 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.ContentMapperFactory - Mapping: Umbraco.Grid
 2017-02-03 12:03:19,467 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Looking for view: macro
 2017-02-03 12:03:19,467 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Looking for view: macro
 2017-02-03 12:03:19,468 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Looking for view: macro
 2017-02-03 12:03:19,468 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Looking for view: macro
 2017-02-03 12:03:19,468 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Looking for view: macro
 2017-02-03 12:03:19,468 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.GridMapper - Mapping: grid.media
 2017-02-03 12:03:19,468 [P16972/D8/T1277] DEBUG Jumoo.uSync.Core.Mappers.ContentMapperFactory - Mapping: grid.media
 2017-02-03 12:03:19,471 [P16972/D8/T1277] WARN  Jumoo.uSync.Content.ContentHandler - Error saving Content: System.NullReferenceException: Object reference not set to an instance of an object.
   at Jumoo.uSync.Core.Mappers.GridMapper.ProcessGridValues(String content, Boolean import)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.GetExportIds(PropertyType propType, XElement value)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.SerializeBase(IContentBase item, String contentTypeAlias)
   at Jumoo.uSync.Core.Serializers.ContentSerializer.SerializeCore(IContent item)
   at Jumoo.uSync.Content.ContentHandler.ExportItem(IContent item, String path, String rootFolder)


Thanks.

**Comment by KevinJump** [comment]
In the upcoming release the macro parameters will be mapped. (when in a grid like above.)
