### ISSUE TITLE
Export Content Properties

### ISSUE THREAD

**Issue by ssajami** [KevinJump/uSync3.0#122]
I've got content that has the "Publish at" or "Unpublish at" date/time properties set. 
This data doesn't seem to be included in the data exported for the content.
Is there somewhere to configure this or is it not possible?

**Comment by KevinJump** [comment]
yeah i don't think they are included in the export - that doesn't mean they can't be - I will have a look for the next release

**Comment by KevinJump** [comment]
will be in next release.

**Comment by ssajami** [comment]
Wow, amazing! Thanks so much :)
