### ISSUE TITLE
ContentTypeSerializer doesnt work properly

### ISSUE THREAD

**Issue by takinosaji** [KevinJump/uSync3.0#126]
Consider following serialized DocumentType by uSync:

`<?xml version="1.0" encoding="utf-8"?>
<DocumentType>
  <Info>
    <Key>f275098b-e30c-452b-b4ec-6f8791134e9d</Key>
    <Name>Layout</Name>
    <Alias>layout</Alias>
    <Icon>icon-document</Icon>
    <Thumbnail>folder.png</Thumbnail>
    <Description></Description>
    <AllowAtRoot>False</AllowAtRoot>
    <IsListView>False</IsListView>
    <Compositions />
    <DefaultTemplate>Layout</DefaultTemplate>
    <AllowedTemplates>
      <Template>Layout</Template>
    </AllowedTemplates>
  </Info>
  <Structure />
  <GenericProperties>
    <GenericProperty>
      <Key>513c8af6-01de-4472-9717-6a0216fb663d</Key>
      <Name>Content</Name>
      <Alias>content</Alias>
      <Definition>5aa18bd8-7c29-4631-a46c-b594897a2bfc</Definition>
      <Type>Our.Umbraco.Vorto</Type>
      <Mandatory>true</Mandatory>
      <Validation></Validation>
      <Description><![CDATA[]]></Description>
      <SortOrder>0</SortOrder>
      <Tab>Content</Tab>
    </GenericProperty>
  </GenericProperties>
  <Tabs>
    <Tab>
      <Caption>Content</Caption>
      <SortOrder>0</SortOrder>
    </Tab>
  </Tabs>
</DocumentType>`

If we change ` <Definition>5aa18bd8-7c29-4631-a46c-b594897a2bfc</Definition>` of property to other value which correspond to changing property type for property in umbraco serializer's method IsUpdate returns false since hashes of serialized item with changed definition guid and existing item is the same!

**Comment by takinosaji** [comment]
UPD1: In your XElementTrackerExtension.GetLocalizeduSyncElement you are wiping content of <Definition> node here:

            // in content types we remove Definition for comparision, because for 
            // custom types it can change. 
            if (copy.Element("GenericProperties") != null)
            {
                foreach (var defId in copy.Element("GenericProperties").Descendants("Definition"))
                {
                    defId.Value = "";
                }
            }

**Comment by KevinJump** [comment]
does the Type property not also change when you change the type ? 

the reason it was wipped it to reduce the number of false positives (admitidly in old versions of umbraco) - essencially every false positive will incure a full import of that doctype which is slow. 

on older (like v7.2/3 versions of umbraco this version id changed a lot, and startup times can become real slow because usync is importing stuff it doesn't need to). 

Will need to just confirm that the value doesn't change as much as it use to... :)

**Comment by takinosaji** [comment]
He Kevin. Thx for response. No the difinition is the only what has been changed since new "data type" has the same "type".

**Comment by KevinJump** [comment]
Will regression test and put into the next release.
