### ISSUE TITLE
Better diff support for Grid Layouts with CDATA and preserved line feeds for some PreValues

### ISSUE THREAD

**Issue by davidtwamley** [KevinJump/uSync3.0#128]
We've encountered an issue several times where the json for a grid layout is modified by multiple developers (even simple changes like which grid editors are allowed) on their feature branches and then merging them is difficult because the json is collapsed down to a single line. In these cases we've resorted to extracting out the raw json from both and putting them in beyond compare. It would be very nice though if instead, these values were wrapped in a CDATA and line feeds were preserved.

Here is an abbreviated example of what we see:

```
<DataType Name="Grid - Text Page" Key="" Id="Umbraco.Grid" DatabaseType="Ntext">
  <PreValues>
    <PreValue Id="1134" Value="{&#xD;&#xA;  &quot;styles&quot;: [&#xD;&#xA;    {&#xD;&#xA;      &quot;label&quot;: &quot;Background Image&quot;,&#xD;&#xA;      &quot;description&quot;
    ...58,000+ chars..." Alias="items" />
  </PreValues>
</DataType>
```

We are using LeBlender but I don't think that matters. I believe storing json in Ntext is becoming more popular too so maybe a generic fix would be best. Some suggestions:

* Always use CDATA for PreValue so the line feeds are preserved
* Detect when CDATA for PreValue would be better, maybe any of these:
    - First char is {
    - Value contains \n
    - Character length > 300

Thanks!

**Comment by davidtwamley** [comment]
Looks like https://github.com/KevinJump/uSync/pull/28 is one approach for achieving this.

**Comment by KevinJump** [comment]
yeah - the mappers for the grid (especially le blender) got quite a bit of a rewrite recently, so i need to move the pre-value stuff into the core so its used in the right places. but yet that PR does show the solution. :)

**Comment by KevinJump** [comment]
will have to bump this to a version change release - as it will change the format of the export file.

**Comment by KevinJump** [comment]
IN next version (baring testing)

**Comment by davidtwamley** [comment]
Very nice! Thank you very much 👍
