### ISSUE TITLE
Shorter Paths for Content and Media

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#130]
Content and Media can still get long quickly. with short paths on you can still only get to around 9 levels deep before you hit content path issues. https://our.umbraco.org/projects/developer-tools/usync/usync/85312-usync-filepath-too-long-issue-even-with-use-short-paths-true

- need to look at options to maybe reduce path length even more.

**Comment by KevinJump** [comment]
Test commit , will create folders based on levels and put content in the level folders, so content tree will probibly look like: 

Content\001\content-node\content.config
Content\002\some-child-node\content.config 

uses handler settings. so to turn on ... in usyncbackoffice.config 

    <HandlerConfig Name="uSync: ContentHandler" Enabled="true">
      <Setting Key="levelpath" Value="true" />
    </HandlerConfig>

    <HandlerConfig Name="uSync: MediaHandler" Enabled="true">
      <Setting Key="levelpath" Value="true" />
    </HandlerConfig>      

Can be combined with the shortIds setting - to get even shorter path names (so the item folder name will become the guid). 

This means paths should't Exceed X + 41 (3 + sep + 22 + sep + "content.config") where X is your based path to the usync/data/content folder).

This method makes minimal changes to any of the existing import code (as we just traverse folders anyway). 

There is an update to core to make sure we look for the parentGUID in the config - but this should be minimal impact as everything is guids now.

**Comment by KevinJump** [comment]
yeah - this is coming with a fairly big caveat, you have all the content synced in usync for this to work perfectly. 

if you have nodes on the target that are not in the source, then when the sync comes along, we can't guarantee that the node won't become orphaned and end up at the root of your site. 

this is because level matching requires the parent node to have a guid matching the one we have inside the usync files. if for some reason we don't have that - then we can't find the parent, and we can't put the node in the right place. 

the potential fixes for this would require us to know the proposed path, and while we can work that out, it would slow down the export of nodes, so might be something we need to look into in a later release, to add that now would add a potential slow down in performance and be a bit to big of a change for a patch release.

**Comment by JohnBergman** [comment]
This seems like a pretty common scenario

"if you have nodes on the target that are not in the source, then when the sync comes along, we can't guarantee that the node won't become orphaned and end up at the root of your site."

Imagine a live site were content managers are working, and a dev site were the next version is being created... this would mean that you would not really be able to support that scenario if there is any change of overlap, which seems like it would be common if the developers are creating new templates, datatypes along with some content instances that use the new templates.

Thoughts?

**Comment by KevinJump** [comment]
yeah 

in theory as long as the parent node of any tree is in the target then it 'should be' ok - but as you say if the nodes are not there then you will get the missing tree. 

I might investigate the performance hit of putting some tree searching stuff in, its a bit of a hit to traverse the tree using the back office services, as you are hitting the db every-time, and their will be a lot of child node stuff going on - but if it's something that only happens when usync is using the level mode then it might be ok.

**Comment by JohnBergman** [comment]
I am guessing you could detect that the issue occurs?

If so, you could add a warning in the usync dashboard with a resolve button that would defer the performance hit should it really be needed?
