### ISSUE TITLE
Newtonsoft.Json error when calling import manually

### ISSUE THREAD

**Issue by markwemekamp** [KevinJump/uSync3.0#138]
I've created my own apicontroller to have usync integrate in our continuous delivery workflow where I call `uSyncBackOfficeContext.Instance.Import` manually. For some reason I get the below exception.

> An exception of type 'System.IO.FileLoadException' occurred in Jumoo.uSync.Content.dll but was not handled in user code

> Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I've made 100% sure that version 10 of json.net is never referenced in my project and I've looked at the source code of usync and came to the conclustion version 10 isn't used there either.

When I call import from the usyng dashboard, everything works fine. But for some reason calling similiar code from my own code, I get this exception.

My code:
```C# 
   var actions = uSyncBackOfficeContext.Instance.Import("Content", importFolder, false);
``` 

My handler:
```
<Handlers Group="Content" EnableMissing="false">
   <HandlerConfig Name="uSync: ContentHandler" Enabled="true" />
   <HandlerConfig Name="uSync: MediaHandler" Enabled="true" />
</Handlers>
```

Version: (uSync.BackOffice 3.3.4.740) (uSync.Core 5.6.4.760) [uSync.Content: 3.3.3.740] 
Installed through nuget

Do you have any idea what's going wrong? Was version 10 of json.net referenced sometime in the usync project?

**Comment by KevinJump** [comment]
Hi yeah a version of usync core was released for v7.6 of umbraco by mistake - it has since been unlisted on nuget but if you change the version of usync.core to 5.6.4.740 you should be ok

**Comment by markwemekamp** [comment]
Cool, thanks for the fast reply. It works now

**Comment by KevinJump** [comment]
yeah bad release handling - :(
