### ISSUE TITLE
Branch Dev-7_4 vs Dev-7_5

### ISSUE THREAD

**Issue by tomschimmel** [KevinJump/uSync3.0#140]
Hi, 
I'm a little confused about the naming of the branches. Does Dev-7_5 implicate this branch works best withUM7.5.x / 7.6.x? Or should I clone the Dev-7_4 (main) branch and use it on UM7.5 and above?
Thanks!

**Comment by KevinJump** [comment]
Hi 

yes dev7_4 is the current active branch , when new releases of umbraco come out, there is often a v7_x branch just to check there are no breaking features - but at the moment everything from v7_4 through to v7_6 is compatible. 

**if you want to clone for fixes ect, use dev7_4**

There are some un-released features : user and member syncing : in uSync_3.4 branch - but these will likely be merged back into dev7_4 before release - but if that is an area you are looking at, you should check that code out first.

**Comment by tomschimmel** [comment]
Thanks for the quick reply and explanation! This makes things more clearer. I'm just looking to clone for fixes, patches etc. so i'll be using the dev7_4 branch then. Thanks again and also for making this tool available for all of the Umbraco community!
