### ISSUE TITLE
uSyncActions.config seemingly being ignored

### ISSUE THREAD

**Issue by zpbd** [KevinJump/uSync3.0#146]
We have an issue (possibly related to environment configuration) where the uSyncActions.config file is not working on our QA server, although it works as expected locally.

The client-side request to `/umbraco/backoffice/uSync/uSyncApi/GetActions` is returning `)]}', []` even though the actions file is present and correct, and has the same (read only) permissions as all the other uSync files.

Not sure how to get to the bottom of this.

**Comment by ghost** [comment]
I have also seen that my uSyncActions.config file is being ignored on QA but works fine locally. Doing an import shows me my updates but none of my deletes are occurring. Pressing the "view uSync Actions" button on local shows me my deletes but doing the same on QA doesn't show me anything (even though they have the same content).

I'm using (uSync.BackOffice 4.0.0.760) (uSync.Core 6.0.0.760) and currently doing manual imports.

Any news on what this issue may be on our ends or whether a code fix is required? This will start becoming time critical for my client very soon.

**Comment by KevinJump** [comment]
yep - this is a read only issue on the file. 
workaround is setting that file to read & that will fix it - 

The fix will be rolled up and included in the next release of usync (i am currently managing two releases because of the differences in v7.5 and v7.6 - so i have to do quite a bit of testing)

**Comment by KevinJump** [comment]
will be in next patch release
