### ISSUE TITLE
Best practice installing on existing project

### ISSUE THREAD

**Issue by ruant** [KevinJump/uSync3.0#153]
Hi!
I have some issues getting uSync to work properly on an existing project.
It's been in production for about a year, and what we've been doing to to manually keep track of datatypes/document types etc. etc. while deploying.

In other words, it's been a mess.
What I've done now is to install uSync through the Umbraco package installer in the backend,
Then I copied the uSync/data folder over locally to my local dev environment.
But over the years the dev environment has been cluttered with dev/testing/experiment shit.
So when I do a full export from my dev environment, it writes out all this old crap that really should have been deleted ages ago.

Is there a way I could make uSync delete everything besides what is finds in the uSync/data folder?
Or do I have to do a manual cleanup job?

Another thing I noticed is that a lot of the prevalue id's on the data types will change.
Will that break stuff when I do the sync?

Cheers!

**Comment by KevinJump** [comment]
Hi 

there isn't a direct way to delete everything that is missing (there is some code [work in progress](https://github.com/KevinJump/uSync/issues/81) but its not production ready) 

but if you want your dev site to be only the stuff in usync you could try putting the folders into a new umbraco site.

if you install a blank site (use the same version of umbraco as your live site). and copy the folders. 
* /views
* /app_plugins
* /css
* /scripts
* /uSync
(and any other custom ones you might have)

Then if you start up the site, uSync will put everything from it's folder into the site and you 'should' end up with a clean version of your site. 

It might take a couple of tweaks (making sure you have the right packages and everything) but this way is probably the best way to get something clean. 

_in terms of prevalue ids, they will change but that should be OK - the prevalue id isn' the thing stored in against content, for example the drop-down lists use the Alias value for the id, which shouldn't change._

**Comment by ruant** [comment]
Perfect. Thanks for the quick reply Kevin.

Yeah, doing it from a clean Dev setup, and importing Prod would be the way to go.
Since there has been changes to Prod that isn't reflected in the Dev environment at the moment.

It will be nice to get this up and running.  More control, A LOT more 👍 
Keep up the good work! Awesome product!
