### ISSUE TITLE
Full Export -> Error: An error has occurred. - Access to the path '[...]\uSync\data\DocumentType\settings-root' is denied.

### ISSUE THREAD

**Issue by StefanoChiodino** [KevinJump/uSync3.0#154]
Umbraco version 7.6.6 assembly: 1.0.6456.19226
(uSync.BackOffice 3.3.4.740) (uSync.Core 5.6.4.740)

When I try to full export I get
`Error: An error has occurred. - Access to the path '[...]\uSync\data\DocumentType\settings-root' is denied.`

I tried to add full permissions to "everyone". If I delete the folder and try again it works!

Had a read through the guide, the wiki and the open issues :(

**Comment by KevinJump** [comment]
Hi 

this can happen if the file or folder is open in something else (like a text editor or a command line).

there is also a small chance that during a full export the delete process can trip over itself, i think delete actions at the file level are not always synchronous so the folder may have a delayed write on it, when the delete comes in and it fails :( 

if might be this one again ; https://github.com/KevinJump/uSync/issues/82 so i'll have a dig and see.

**Comment by StefanoChiodino** [comment]
You may be onto something, I just tried on the server and it worked, I'll try to close as many programs as possible, unfortunately it may be VS itself.

**Comment by StefanoChiodino** [comment]
Uhm I closed a couple of programs and now I can't replicate it anymore :(

Guess I'll close this issue unless I can replicate it!

Thank you so much!
