### ISSUE TITLE
Using a virtual directory to uSync/data fails when creating new data types

### ISSUE THREAD

**Issue by tomschimmel** [KevinJump/uSync3.0#163]
Hi KevinJump, 

I've used usync since a while now with a virtual directory set in IIS. While using um7.7 with the latest uSync release everything work perfect when creating a new document type (with template), media type, member type etc. However if I create a new datatype the virtual dir mapping is ignored and .config files are created straight into the website directory. 

I know I could also set the export path in the uSyncBackoffice.config file but with our set-up we would like to manage this via virtual folder mappings.

Do you might perhaps have an idea where things go wrong?

**Comment by KevinJump** [comment]
Hi I've had a quick look - but i suspect its thread based and not a super quick fix :(

Historically Datatypes save slightly different than other items in uSync. 

The original issue is that the  `DataType.Saved` event in umbraco fired before all of the data type is saved (specifically the prevalues) - this means usync has to wait a little while before saving the dataType to disk or it won't get everything. 

To Achieve this uSync queues the datatype saves up and sets a timer if no other saves have happened, in-between (and reset the timer) then it goes through the queue and saves the datatypes to disk. 

It would appear this timed event is happening in a different thread, and for some reason isn't getting the virtual directory config from the site when it asks for the path of the folder . 

there are a few things that need investigating here:

1. Does umbraco's DataType Saved event now fire after the preValues are saved ? - if it does we can ditch the queue.
2. Equally is there now a preValue event that we can trust - and trigger from that?
3. Can we do this in a diffrent way so the MapPath functions still work
4. do we need to pass the path into the Queue from the good thread - (this would actually make DataTypes even more unique in the way they work vs everything else).

Looking at the orginal issue : http://issues.umbraco.org/issue/U4-5353 then the answer should be 1. and we can just drop the whole work around issue - but I will need to do some testing... 

but in theory, its remove the queuing bit and directly put the `SaveToDisk(item);` call in the events. - but uSync supports Umbraco 7.4+ so it would need to be tested on a few versions. 
https://github.com/KevinJump/uSync/blob/Dev-v7_7/Jumoo.uSync.BackOffice/Handlers/DataTypeHandler.cs#L207

**Comment by KevinJump** [comment]
In 4.0.4 release

**Comment by tomschimmel** [comment]
Hi KevinJump,
Thank you for the reply and the edits. I'm not very familiar with the datatype handler but I can see you dropped the whole delayed save so I guess testing with other umbraco versions came out ok?
Thanks a lot for your time looking in to this, it will help us a lot!
