### ISSUE TITLE
Add support Content Templates

### ISSUE THREAD

**Issue by grifin85** [KevinJump/uSync3.0#166]
Thank you for your product. 
Will be cool, if you add **Content Templates**

**Comment by KevinJump** [comment]
Hi,
uSync.ContentEdition supports Content Templates - but they are turned off in the config by default

if you change the handler value from false to true they should be synced (you will need to do an export to get the existing ones created) 

the existing line should be in your config in the default handler group
```
   <!-- Umbraco 7.7 - Content Templates (Blueprints) --> 
    <HandlerConfig Name="uSync: ContentTemplateHandler" Enabled="false" />
```

so once changed 
```
   <!-- Umbraco 7.7 - Content Templates (Blueprints) --> 
    <HandlerConfig Name="uSync: ContentTemplateHandler" Enabled="true" />
```
