### ISSUE TITLE
History tab uses different date formats

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/uSync3.0#169]
Hi, so I was looking at the history tab in Usync and noticed that the date format for the entries is inconsistent. 

I've not had a chance to look through the code to see where it comes from but thought it should be flagged.

Import format: 27/03/2018 13:59
Startup format: 3/27/2018 1:50 PM

**Comment by KevinJump** [comment]
I think its a server / user thing (possibly) the date gets written out into the xml file at the end of the export using `DateTime.Now.ToString("g")` - which i think can swap around depending on the culture the thread is running under. 

I am going to swap it to use 'u' which will give a nicer more consist ant time reading - independent of server culture (well bar language changes for the names of the days)
