### ISSUE TITLE
Saving Umbraco.DropDown changes all the prevalue IDs

### ISSUE THREAD

**Issue by StefanoChiodino** [KevinJump/uSync3.0#175]
I need to ammend a dropdown and noticed uSync changes all prevalue IDs.
![image](https://user-images.githubusercontent.com/1428893/39061584-ae72ef36-44bc-11e8-8593-076ed5dbfb10.png)
The only change I've made here is to add a space in the middle of one of the descriptions.
Some ID have been switch with another (second prevalue ID has become the first prevalue ID) and some have changed completely.

uSync 4.0.2
uSync.Core 6.0.2

Cheers

**Comment by KevinJump** [comment]
not sure but does this change how the content displays the picked values ? 
the Alias value is usally what is stored in the content item (i think) and uSync actually ignores the ID as part of what it does. 

in the background uSync using back office calls that set the collection of prevalues from a dictionary, i think this is what is moving the IDs around but i was under the impression from testing it didn't really matter - if however it now does (it might have changed internally) then we can look at doing this a different way.

**Comment by StefanoChiodino** [comment]
Thanks for your quick reply.

I haven't tried going ahead with it, however seems to me that ultimately that id is what is stored in the db, so this would cause caos! It's stored as the string value in the cache, so it may not break immediately, but I'd guess it will load the wrong value, or no value at all if none exist in the new pool of prevalues, in the backoffice.

That being said, I'm just checking the DB and the values in uSync don't match, so that may be why. I'll try to fix that and see if after they are in sync the problem persists.

**Comment by KevinJump** [comment]
yeah The ID value is never set directly - its also never read directly from the xml - it's only really there for historical reasons 😦 and are stripped before we do any comparisons to work out if there is a change to be applied. 

The Umbraco Core API call we use is [DataTypeService.SavePreValues](https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Core/Services/DataTypeService.cs#L494)   This takes the string (alias) and value (PreValue) as part of a dictionary object,  the PreValue object does have an ID value (which cannot be changed) but we get this is loaded in from a call to `GetPreValuesCollectionByDataTypeId `which gives us what is in the DB. 

So I am not sure if a) we can do it differently, and b) if the actual IDs are changing in the DB when we save stuff. (any more then they are if you do this change manually in the back office).

**Comment by StefanoChiodino** [comment]
I've just restored the live DB on the dev DB. There are 2 entries in the dropdown that somehow are the same and it doesn't let me save it as it is, so I'm just adding a space in the middle of one of them, the definition produced by uSync now changes 3 IDs completely.

**Comment by StefanoChiodino** [comment]
Just tried adding the same values to another - pretty much identical - drop drown data type, and it worked just fine. Maybe it's the duplicate entry (that again, no idea how it got there) throwing it off?

**Comment by KevinJump** [comment]
I have seen sometimes that DB Restore (depending on versions or how its down) can reset the identity column of a table, this means SQL will stat issuing IDs for rows starting back at 1, and these will clash with the ones in the table and you can't insert anything -  Could be that (or some deep dark bit of umbraco doing it) 

but it does sound like an issue with the data in your db somewhere.

**Comment by StefanoChiodino** [comment]
Considering these dropdowns were very similar and only one is giving problems I'm keen on the problem being based on the fact that a value is duplicated. Do you think that's possible?

**Comment by StefanoChiodino** [comment]
I've picked this up again and it seems to me that uSync is using the ids that are on the db. I think it's Umbraco misbehaving by changing several ids without a reason :(

Thanks for your help anyway!

**Comment by KevinJump** [comment]
Hi there is something to some of this - you should look at issue #176 - I am working on something that will mitigate the majority of cases (i hope)
