### ISSUE TITLE
Updating a property requires a second doctype save to update "Type"

### ISSUE THREAD

**Issue by karltynan** [KevinJump/uSync3.0#178]
When you create a property and save the doctype, I can see it update the `Type` and `Definition` in the `def.config` XML as expected (i.e. `Type` is set to `Umbraco.Textbox`).

But, if I then change the property to another type (i.e. checkbox) and save the doctype, the `Definition` updates but the `Type` remains as `Umbraco.Textbox`.

Saving the doctype a second time fixes this issue by updating both the `Definition` and the `Type` as expected.

**Version:** uSync.BackOffice 4.0.5.0) (uSync.Core 6.0.5.0)
**Umbraco:** version 7.10.4

**Comment by KevinJump** [comment]
🤕 I suspect there are timing issues (there have been in the past - i thought they had all gone) - the trigger events in umbraco might be firing before the actual full update to the doctype is complete 😢 

Will investigate this....

**Comment by karltynan** [comment]
It's very edge case 😃 - I only noticed because I saved from true/false to a Vorto true/false.

**Comment by KevinJump** [comment]
ohhh not as painful as i had thought :) but quite odd. (don't worry none of this matters  - i am just writing it down for my own benefit) 

when the save event fires, not all of the property's properties are fully updated : 

property.dataTypeDefinition has been updated - and we use this to get the datatype and then the key value we save into Definition. 

but property.PropertyEditorAlias isn't updated (hence the issue). 

however as we are getting the full property editor alias to get the key, we can just get the propertyeditoralias of the datatype directly, and then it all works.

quick test and all other property properties we use appear to be updated fine :)

**Comment by karltynan** [comment]
Amazing! I would have been happy just clicking save twice for the next few months to be honest... #h5yr
