### ISSUE TITLE
uSync not correctly syncing the sortorder of prevalues when amount of prevalues exceeds 10

### ISSUE THREAD

**Issue by DempseySbaiz** [KevinJump/uSync3.0#182]
Hello,

I think there is a bug in the uSync import of prevalues. I have a prevalue with 13 values as you can see in the first attachment. The order is exactly correct as I want it in this file. 
When I import this file with uSync, the sortorder of the prevalues is not correct, as you can see in the second attachment.

When I started to look what went wrong in the database, I noticed the following pattern: 
If there are more than 10 prevalues, the aliases will become larger than 1 digit. The default sorting for the alias field is as a text-field, because the alias can contain more than numbers. But when you sort a number as a text field, the sorting is wrong, and it will sort like this: 0 - 1 - 11 - 12 - 13 - 2 - 3 - ....
What I expect when sorting prevalues with only Id's in the alias field is the following : 0 - 1 - 2 - 3 - 4 - ...

As you can see in the last screenshot, I think this is what is going wrong with the import.
Could you verify and confirm that this is an issue? Or am I doing something wrong?

Kind regards,
Dempsey

Source uSync file:
![usyncsource](https://user-images.githubusercontent.com/35026511/41535267-fc9a7f26-7301-11e8-8656-af5a6ac73746.PNG)

Result in Umbraco:
![umbracoresult](https://user-images.githubusercontent.com/35026511/41535408-7c66ed66-7302-11e8-8404-73b4a5eef7f4.PNG)

Result in the Umbraco database:
![dbresult](https://user-images.githubusercontent.com/35026511/41535269-fe8836e8-7301-11e8-8176-bd03ab4f8993.PNG)

**Comment by KevinJump** [comment]
yeah i am sure we use to store the sort order too, but maybe i am just remembering something else . 

it does look like something is sorting the xml by alias, before we get our values to it, i will look at adding (back?) the sort order and using that to sort the lists.
