### ISSUE TITLE
template changes not taken into account

### ISSUE THREAD

**Issue by beumsk** [KevinJump/uSync3.0#196]
We tested Usync to copy dev changes to production environment. 
All the content changes were copied well. But template changes were not.
Any idea why?

**Comment by KevinJump** [comment]
Hi

the actual content of the template files isn't synced by usync - only the internal DB (and tree) settings. you will need to also copy your templates (from the views folder) to include the changes on the production server.

**Comment by KevinJump** [comment]
this is the intended behavior - closing this issue (unless there is something else wrong?)

**Comment by beumsk** [comment]
Thanks Kevin !
It solved our issue.
