### ISSUE TITLE
Inappropriate properties are converted to Guids

### ISSUE THREAD

**Issue by thecontrarycat** [KevinJump/uSync3.0#2]
It appears that the code that maps integer Ids to Guids is being ran indiscriminately on export.  This is particularly apparent when you have a property of type TextString where any 4 to 10 character number can be converted to a Guid if it matches a node in the CMS.

e.g. ExecutableName property with value of "PR1051.exe" has a value of "PR3D08C9E2-D369-426A-875C-19685F7FABBC.exe" after export.

Should TextString properties be mapped at all?

**Comment by KevinJump** [comment]
yeah, I need to do some value mapping stuff and put something in the config to determine if the id should be mapped.

**Comment by KevinJump** [comment]
Mapping is now separated out - and you can define what property types map in the uSyncCore.Config 
see f5e24d9a57bafda9778528fa1abfd9a01653dde5
