### ISSUE TITLE
Cannot 'Edit on GitHub' in ReadTheDocs site

### ISSUE THREAD

**Issue by lcichanowicz** [KevinJump/uSync3.0#201]
Hi.  I was going to fix a typo on this page:
https://usync.readthedocs.io/getting-started/

When I click its 'Edit on GitHub' link (https://github.com/KevinJump/uSync/tree/Dev-v7_4/docs/edit/master/docs/getting-started.md), I get a 404.

**Comment by KevinJump** [comment]
fixed !
