### ISSUE TITLE
Unable to export datatypes and contenttypes on umbraco 7.15.0

### ISSUE THREAD

**Issue by DempseySbaiz** [KevinJump/uSync3.0#224]
Hey Kevin,

I think there is still an issue with Umbraco 7.15.0 and your latest fix (uSync v4.0.12.0).
I can't export any datatypes or content types since the upgrade.

For example, for datatypes, it gives me the following error:

> Failed to save dt - nc - bericht - System.NotSupportedException: The passed in type is not supported
> at Umbraco.Core.Services.EntityService.<>c__261.<GetAll>b__26_0() at Umbraco.Core.Mandate.That[TException](Boolean condition, Func1 defer)
> at Umbraco.Core.Services.EntityService.GetAll[T](Int32[] ids)
> at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.GetEntityPath(IUmbracoEntity item)
> at Jumoo.uSync.BackOffice.Handlers.DataTypeHandler.ExportToDisk(IDataTypeDefinition item, String folder)
> 

So it fails on the GetAll function that you changed in the last uSync release.
Could you check this out please? Thanks!

**Comment by KevinJump** [comment]
Fixed as a child of #223 in v4.0.13

**Comment by DempseySbaiz** [comment]
Just tested it and it seems to work again. 
Thx for the great work Kevin!
