### ISSUE TITLE
usyncbackoffice.config archive flag may not work

### ISSUE THREAD

**Issue by JohnBergman** [KevinJump/uSync3.0#241]
I have the flag set to false (Archive Verison)...
  <ArchiveVersions>false</ArchiveVersions>

But I still see this in the debug log.

2019-11-11 20:37:32,085 [P35124/D2/T21] DEBUG Jumoo.uSync.BackOffice.Helpers.uSyncIOHelper - Archive: D:

**Comment by KevinJump** [comment]
Hi 

it works, but the debug line is before the check is carried out. 
https://github.com/KevinJump/uSync/blob/v4_master/Jumoo.uSync.BackOffice/Helpers/uSyncIOHelper.cs#L60
