### ISSUE TITLE
[BUG] How to uninstall usync without crash the project

### ISSUE THREAD

**Issue by deenmkt** [KevinJump/uSync3.0#247]
** This Repo is for uSync v4 on Umbraco 7 - please raise uSync 8 issues on the uSync 8 repo**
https://github.com/KevinJump/uSync8/issues

I'm running uSync.BackOffice 4.0.9.0) (uSync.Core 6.0.9.0) [uSync.Content: 4.1.5.0] and umbraco 7.12.2 and I do need to uninstall Usync.
What is the corret what to uninstall.
I've tried to do it throught umbraco package uninstall and the following error appears:

Could not load all types from "Jumoo.uSync.Content, Version=4.1.5.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:

**Comment by KevinJump** [comment]
Hi, sorry for no reply, just cleaning up the issues now :( 

for future reference you have to uninstall packages in the reverse order to how you installed them, so you need to remove uSync.ContentEdition before uSync. 

if you do get hte following error removing the usync dlls from the site's bin folder should restore access to the site.
