### ISSUE TITLE
On-demand synchronisation

### ISSUE THREAD

**Issue by agrath** [KevinJump/uSync3.0#248]
Hey @KevinJump 

Firstly, thank you so much for creating uSync, it has really altered the way we do Umbraco development in our team.
We use the schema synchronisation via our deployment server with our dev site (local machines) committing schema changes then the staging & live sites (hooked to different branches) importing as changes move through the environments.
To release changes to an environment we merge from master->unstable->stable

In the past, we've tried using courier but had no end of problems with things getting out of synch, missed properties, duplicate nodes, crashes etc.
We are investigating if we can use uSync.Content to copy content between Staging and Live, but not from our dev. 
We ideally would like to use this in a similar capacity to the way courier [is intended to] work[s], 
e.g. being able to configure content on staging or live, then ship it/synchronise it to another environment.

From what I can tell, uSync.Content works similarly to the schema with the content being saved to files, and as we push schema dev->staging->live that doesn't seem like it would be a good idea to enable (our dev content is often absolute rubbish (or a clone of staging with altered stuff) to test various features etc.)

I am wondering if something could be acheived using snapshots and an api to push the snapshots between the environments along with some UI components to allow this to be triggered by a content editor rather than a developer.

Any thoughts? have you considered this workflow before?

**Comment by KevinJump** [comment]
Hi,

this is pretty much what [uSync.Complete/Publisher](https://jumoo.co.uk/usync/publisher/) does for Umbraco 8, allowing you push & pull content between sites.

We don't have any plans to back port it to umbraco 8 at the moment, mainly because that would be **a lot** of work
