### ISSUE TITLE
[BUG] MediaHandler Setting of useshortidnames is not applied

### ISSUE THREAD

**Issue by marcemarc** [KevinJump/uSync3.0#363]
**This Repo is for uSync v4 on Umbraco 7 - please raise uSync 8 issues on the uSync 8 repo**
https://github.com/KevinJump/uSync8/issues

### About your installation
**Umbraco Version**: 
**uSync Version**: 7.7.7
Backoffice: 4.0.2.0
Core: 6.0.3.0
Content: 4.1.9.1

### Description of issue
Was doing a full export of content and media for a new uSync Migration. Found missing media in the export due to long file names
Therefore wanted to switch the media handler to use useshortidnames - but keep everything else human readable.

I applied the setting to the MediaHandler it appeared to be ignored, applied the setting to the content handler, recycled app pool etc, all is fine for content it observes the new useshortidnames, discovered the levelpath setting, added that too both, immediately observed by content - but media still writes out the folder names...

![image](https://github.com/KevinJump/uSync-Legacy/assets/260802/f60cf332-d10d-42c4-9679-a7aadf44a5ae)

switched the global UseShortIdNames to be true

![image](https://github.com/KevinJump/uSync-Legacy/assets/260802/5c910ab2-9c30-40b2-9aaf-594517560c85)

And now Media is exporting out using the shorter file names.

So feels like I have either put config in wrong place - the Media Exporter doesn't use the MediaHandler for Content edition that's something else... you want to add the setting to the MediaMediaContentMediaHandler you fool...

or

I has made a typo in the config - I has cut and pasted the content ones that work to be sure

or

Both MediaHandler and ContentHandler inherit from BaseContentHandler (and that is where the global setting overrides the handler setting) 

So question is when it 'loops' through the '_settings; in LaodHandlerConfig

![image](https://github.com/KevinJump/uSync-Legacy/assets/260802/cdf2db06-5bc4-49b1-b1ef-587eea8b4aeb)

why it gets a false for MediaHandler but true for ContentHandler... 

Need to fork it and see what is going on, but thought I'd raise an issue in case I'm doing something monumentally stupid!

**Comment by KevinJump** [comment]
yeah looking at the code i can't see why that won't work 🤔  - Will have to take a look. (now that i've downloaded vs 2019, and reverted a load of depandabot crud that breaks the build!

**Comment by KevinJump** [comment]
Found it - the MediaHandler wasn't a `ISyncConfigHandler` so the code to load the config per handler wasn't getting called - (so it only had global settings).

**Comment by marcemarc** [comment]
aha!
thanks!
