### ISSUE TITLE
Usync not syncronizing ContentType after creation.

### ISSUE THREAD

**Issue by Mobsan** [KevinJump/uSync3.0#42]
Steps:
- Create content
- Usync the content to another installation
- Change the ContentType (Change Document Type)
- Usync the content to the same installation
  The type is not updated.

Suggestions (needs tweeking)
ContentSerializer:91

``` csharp
IContentType contentType = _contentService.FindContentTypeByAlias(type);
if (item.ContentTypeId != contentType.Id)
{
    item.ChangeContentType(contentType);
}
```

(the type variable is only used in the creation of the content)

The problem here is that FindContentTypeByAlias is a private function and not accessible. To get this to work, we would need Umbraco to change the interface of IContentService (how close are you working with the Umbraco team?).

The other way is to extend Umbraco source code with a function ChangeContentType accepting a string(TypeAlias).

What do you think about this?

**Comment by Mobsan** [comment]
```
        IContentType contentType = _contentTypeService.GetContentType(type);
        if (item.ContentTypeId != contentType.Id)
        {
            item.ChangeContentType(contentType);
        }
```

**Comment by KevinJump** [comment]
yeah - i will add and test and see how that works.

**Comment by KevinJump** [comment]
Fixed in code, will roll up into the next release.
