### ISSUE TITLE
Map NestedContent

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#43]
uSync doesn't have a nestedContent Mapper, but adding one shouldn't be to hard (infact @madsoulswe has most of one written already).

**Comment by madsoulswe** [comment]
I see now that some content don't get exported and renders errors when saving xml.
CDATA is needed on tinymce (html) and json, and almost everything? =)

Example: 
type: RTE
alias: preamble

```
<preamble>
    <p>
      <span>asdasd<br /></span>
    </p>
  </preamble>
```

**Comment by KevinJump** [comment]
yeah, its a bug in the logic calling the mapper i think. 

it is unwrapping the cdata on sections that need mapping but then not putting them back.

**Comment by KevinJump** [comment]
Hi

I think this is now working if you want to test then you just need the dll and .config from the core package. 

https://github.com/KevinJump/uSync/tree/Dev-v7_4/umbPackage/uSync.Core
- I am just going to test a couple of things and wrap this into a release .

**Comment by madsoulswe** [comment]
Tested it (on a pretty large site) and....

![its_working_star_wars](https://cloud.githubusercontent.com/assets/7071187/14937379/fb0895c4-0f05-11e6-8b35-ca5b218b2a61.gif)

**Comment by KevinJump** [comment]
Slight bug - didn't work property if the nested doctype was formed of composistions (basically needs to call CompositePropertyTypes not propertytypes) - but that is fixed in the code now.

**Comment by KevinJump** [comment]
Will be in next release (soon)
