### ISSUE TITLE
Media Item Master/Composition troubles

### ISSUE THREAD

**Issue by lucasch** [KevinJump/uSync3.0#52]
I've been playing around with media types and folders and there appears to be some conflict with Master and Folder when exporting/importing media types.

Given the way the back office behaves, I don't think Master is really necessary or relevant for media types.  The back office never really supported inheritance of media items well, and now it looks like it doesn't even show the expansion arrows in such cases.  

The problem, as it stands, is that uSync exports media items with their first composition as their master and skips any folder processing.  When these items are imported, they're pathed under the first component, and "disappear" in the back office.

It seems to me that, on import, media types' Master can be shoved in a composition and not have any bearing on the path of the item.  The Folder property can then be used to generate the appropriate path and parent id.

**Comment by KevinJump** [comment]
yes - The no inheritance on content types of the v7.4 beta wasn't fully rolled back on media types, as you say it's probably a case that we leave it to compositions, 

I will review the folder stuff too, but that should work the same as content types.

**Comment by lucasch** [comment]
Thanks, please let me know if there's anything I can provide / do to help out!

**Comment by KevinJump** [comment]
I think it just took a bit of judicious snipping the dll in https://github.com/KevinJump/uSync/tree/Dev-v7_4/umbPackage/uSync.Core contains the compsition changes and the master stuff if you want to test.

**Comment by lucasch** [comment]
It's looking good to me, thanks!

It's worth noting that if someone (like I did) had inheritance in their legacy uSync media files, that'll will no longer work.

**Comment by KevinJump** [comment]
yes, that's the breaking change I suppose - but under umbraco 7.4 You can't do anything with those now inherited types? and if they can't be recreated on a new target site? 

I'll have a quick check because with just the changes to the export (not writing out a master) I think the import still works. so then you could have the master on (an old) import - but that isn't going to create the structure because we can't have it?

**Comment by lucasch** [comment]
If the Master is populated on an old import file, it'll still get added to the MediaType path via DeserializeBase.  The MediaType will get created but it will be inaccessible (pathed under it's Master) and therefore uneditable in the back office which would require a DB transaction to fix.

**Comment by KevinJump** [comment]
Ahh i get it, we could (as you have already said at the top) take the master (if set) and make it a composition.

**Comment by lucasch** [comment]
Yes, that would be ideal in the case of MediaTypes.  

I was looking at what it would take to refactor this as the DeserializeBase is shared between MediaTypes and ContentTypes so I figured I'd come here an investigate.  The Master handling could be split into the respective Serializer classes I suppose, and called after DeserializeBase?

**Comment by KevinJump** [comment]
Yes It's a bit of a pain now they are different, the default media serialize behavior is to essentially overwrite the master as set in DeserializeBase - and you have to remember MemberTypes also calls the same base class, so we need to make sure we don't break them (if they are indeed working like this!)

**Comment by KevinJump** [comment]
OK, this commit https://github.com/KevinJump/uSync/commit/d70d868c448152b02cc88251f3558049743e114d moves any master values into the compostion section, We can assume that the compositon section is empty becasue up until now we've never set it. 

We also have to set the parent even when it's -1 because we might be moving something from it's previous location which would now be hidden.

**Comment by lucasch** [comment]
This looks good.  I'll do some further testing in the morning as I have to sign off for the day pretty shortly.  Thanks for looking into this!
