### ISSUE TITLE
Content-mapping sometimes replaces year-date (YYYY) with ids

### ISSUE THREAD

**Issue by madsoulswe** [KevinJump/uSync3.0#57]
We hade an issue where 2016 (and other dates) was replace all over the site

Example page, som these were replaced with id's
[History page](http://valutec.ca/about-valutec/history/)

**Comment by KevinJump** [comment]
Yep, 

the content mapper for tiny MCE is a bit blunt at the moment, it needs to be updated to use better RegEx Expressions to capture Ids inside the content .

For my reference: the following gets locallinks in a tiny mce editor

`localLinkRegex = @"((?<=localLink:)([0-9]+)|(?<=data-id="")([0-9]+))";`

**Comment by KevinJump** [comment]
This update - should fix this - it's wrapped up in some other Mapper Updates, but when they are done, this will be released too.
