### ISSUE TITLE
Target consistent .NET framework version

### ISSUE THREAD

**Issue by lucasch** [KevinJump/uSync3.0#58]
I've noticed that the uSync projects are targeting a mix of .NET framework 4.5.1 and 4.5.2.  Would it be possible to just target 4.5 across all the uSync projects?  It doesn't appear there is any specific need to target a later version.

I ask because we have use uSync in our own custom sync controller that toggle handlers based on the sites' needs and we're still using framework 4.5.  I'm currently compiling from the Git source but would much rather use the nuget package!

**Comment by KevinJump** [comment]
yep - thats something i should sort out!

**Comment by KevinJump** [comment]
As an aside, I want to improve control over the handler section, so any thoughts on that would be great. https://github.com/KevinJump/uSync/issues/59

**Comment by KevinJump** [comment]
Merged into both branches of current dev, will be true on the next release
