### ISSUE TITLE
uSync 404 Error (using NuGet Package Restore)

### ISSUE THREAD

**Issue by LoganLehman** [KevinJump/uSync3.0#63]
I am running into an issue where after performing NuGet package restore (from a new pull of our branch) I am getting the following error from the developer section:

**Request error**: The URL returned a 404 (not found): _backoffice/uSync/uSyncApi/GetSettings_

![usync_error](https://cloud.githubusercontent.com/assets/1081678/17254319/275e0a2e-5569-11e6-88fd-b2a840f1ff23.png)

It works fine on my machine (where the project was initially created) - but does not work on other machines I restore from. This is the folder for USync as it stands (on all machines):

![usync_app_plugins](https://cloud.githubusercontent.com/assets/1081678/17254762/ff4dcf36-556a-11e6-9601-91863525aa93.PNG)

and here is the NuGet Screen:

![usync_versions](https://cloud.githubusercontent.com/assets/1081678/17256329/ecc9daa6-5571-11e6-90ba-aaff2059e560.PNG)

I am not sure how to fix this problem 100%, so I wanted to report it.

**Comment by KevinJump** [comment]
Hi 

sounds like the old dashboard, is still there, but that's probibly something in the nuget package not upgrading properly. I'll have a look.

you don't however need uSync and uSync.Backoffice, they are in effect the same package _(this just prompted me to actually figure out how to fix that too. I am going to make BackOffice an empty nuget package that just has uSync as an dependency)._

**Comment by LoganLehman** [comment]
@KevinJump ,

Thanks for looking into this! I will look for a workaround in the meantime as well.

**Comment by KevinJump** [comment]
Hi i think it might be because the upgrade has left the dll Jumoo.uSync.BackOffice.ui.dll in the bin folder, 

this dll isn't needed anymore (the ui stuff has been put into the main dll). so i think if you have this DLL you can just remove it.

**Comment by LoganLehman** [comment]
@KevinJump 

I will go ahead and check this out soon and get back to you. Thanks for the reply.

**Comment by KevinJump** [comment]
yeah - I have moved this for me, because i haven't yet had a chance to look at making the nuget package do it in the last release - but if ui dll is there and you remove it - that should fix it.

**Comment by LoganLehman** [comment]
@KevinJump,

I do not have the .ui.dll in my bin folder, and neither to the other machines that I restored to (my coworkers machines). Unfortunately, we may be barking up a weird ally. Here is my references and bin:

![jumoo](https://cloud.githubusercontent.com/assets/1081678/17342980/669fdcae-58b0-11e6-9511-ac8cd5656841.PNG)

![jumooref](https://cloud.githubusercontent.com/assets/1081678/17342981/66b76068-58b0-11e6-8f29-d6866213f153.PNG)

Should I remove BackOffice all together?

**Comment by LoganLehman** [comment]
> Hi
> 
> sounds like the old dashboard, is still there, but that's probibly something in the nuget package not upgrading properly. I'll have a look.
> 
> you don't however need uSync and uSync.Backoffice, they are in effect the same package (this just prompted me to actually figure out how to fix that too. I am going to make BackOffice an empty nuget package that just has uSync as an dependency).

@KevinJump - In accordance to this statement, I removed the USync.BackOffice NuGet project from my project, and it completely removed my App_Plugins/USync folder, and now the dashboard will not load.

**Comment by LoganLehman** [comment]
I take that back, I updated from the latest NuGet package, and it restored the USync folder. However, now I am getting a dashboard configuration error (it created a duplicate - **I fixed it but just to let you know**):

![servererrorconfig](https://cloud.githubusercontent.com/assets/1081678/17343441/89057612-58b2-11e6-85f9-0133f2178b49.PNG)

Onto testing NuGet Restore on other machines

**Comment by KevinJump** [comment]
yeah, the package is using .transform files. but i think it will be more reliable if it used xdt files (which is how i've just done the content mappers package) 

I will have a look at that, i think they will be more reliable. in adding/removing the sections

**Comment by LoganLehman** [comment]
I have confirmed this to be resolved. Thanks @KevinJump
