### ISSUE TITLE
uSync Startup Error

### ISSUE THREAD

**Issue by LoganLehman** [KevinJump/uSync3.0#74]
Hey @KevinJump,

Got another one for you. I went ahead and pushed my changes yesterday to git and one of my team members pulled down and got this error:

![usyncerror](https://cloud.githubusercontent.com/assets/1081678/17779489/ac372e7a-651c-11e6-8ad5-7b7bba691485.jpg)

We can't even get into the Umbraco backend on his machine. However, on mine I can (where the changes originated from). I tried to do a full export and commit those files, but to no avail. I am at a loss as I cannot get into his backoffice.

**Comment by KevinJump** [comment]
Hi, 

if you turn off, Import in the usyncbackoffice.config file you should be able to get into the back end of this umbraco install.

Can you have a look in the app_data/logs/umbracotracelog.txt for this and see if there is more of an error? 

Kevin

**Comment by LoganLehman** [comment]
@KevinJump,

The following seems to be all I am getting here (repeating every time we go to the backoffice):

> 2016-08-18 08:07:36,635 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 41 Items 4 changes 0 failures
> 2016-08-18 08:07:36,635 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: Template
> 2016-08-18 08:07:36,673 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 2 Items 0 changes 0 failures
> 2016-08-18 08:07:36,673 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: DocumentType
> 2016-08-18 08:07:36,979 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 3 Items 0 changes 0 failures
> 2016-08-18 08:07:36,979 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: MediaType
> 2016-08-18 08:07:37,135 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 10 Items 0 changes 0 failures
> 2016-08-18 08:07:37,136 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: Languages
> 2016-08-18 08:07:37,150 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 1 Items 0 changes 0 failures
> 2016-08-18 08:07:37,150 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: DictionaryItem
> 2016-08-18 08:07:37,151 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 0 Items 0 changes 0 failures
> 2016-08-18 08:07:37,151 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: macro
> 2016-08-18 08:07:37,151 [P31012/D14/T37] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 0 Items 0 changes 0 failures
> 2016-08-18 08:07:37,208 [P31012/D14/T37] INFO  Umbraco.Core.PluginManager - Starting resolution types of Umbraco.Core.PropertyEditors.IParameterEditor
> 2016-08-18 08:07:37,210 [P31012/D14/T37] INFO  Umbraco.Core.PluginManager - Completed resolution of types of Umbraco.Core.PropertyEditors.IParameterEditor, found 0 (took 2ms)
> 2016-08-18 08:07:37,816 [P31012/D14/T37] WARN  Umbraco.Core.Persistence.Repositories.VersionableRepositoryBase`2[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Umbraco.Core.Models.IContent, Umbraco.Core, Version=1.0.5948.18141, Culture=neutral, PublicKeyToken=null]] - The query returned multiple property sets for document definition 1118, Default
> 2016-08-18 08:07:37,899 [P31012/D14/T37] ERROR Umbraco.Core.CoreBootManager - An error occurred running OnApplicationStarted for handler Jumoo.uSync.BackOffice.uSyncApplicationEventHandler
> System.InvalidOperationException: Sequence contains more than one element
>    at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()
>    at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
>    at Umbraco.Core.CoreBootManager.<Complete>b__a(IApplicationEventHandler x)
> 2016-08-18 08:07:37,969 [P31012/D14/T37] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
> System.InvalidOperationException: Sequence contains more than one element
>    at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()
>    at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
>    at Umbraco.Core.CoreBootManager.<Complete>b__a(IApplicationEventHandler x)
>    at Umbraco.Core.EnumerableExtensions.ForEach[TItem](IEnumerable`1 items, Action`1 action)
>    at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
>    at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
>    at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
> 2016-08-18 08:07:37,982 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
> 2016-08-18 08:07:37,982 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Waiting for tasks to complete
> 2016-08-18 08:07:37,985 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Tasks completed, terminated
> 2016-08-18 08:07:37,985 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Terminating
> 2016-08-18 08:07:37,985 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Waiting for tasks to complete
> 2016-08-18 08:07:37,985 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledPublishing] Tasks completed, terminated
> 2016-08-18 08:07:37,986 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Terminating
> 2016-08-18 08:07:37,986 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Waiting for tasks to complete
> 2016-08-18 08:07:37,986 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [KeepAlive] Tasks completed, terminated
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Terminating
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Waiting for tasks to complete
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [LogScrubber] Tasks completed, terminated
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Terminating
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Waiting for tasks to complete
> 2016-08-18 08:07:38,088 [P31012/D14/T808] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [ScheduledTasks] Tasks completed, terminated

**Comment by KevinJump** [comment]
Hi 

if you can add the following to the log4net.config and you will get more debugging from uSync, which might help us pinpoint which thing is causing the error. 

`<logger name="Jumoo.uSync"><level value="Debug"/></logger>`

and If you bump that instance upto the latest uSync you might get a better error (you can just copy the uSync.Core.dll and uSync.BackOffice.dll from the latest package if you can't get into the solution or nuget it) 

but it looks like one of hte doctypes (specifically 1118) has version issues :(

**Comment by LoganLehman** [comment]
Oh yeah, 

We got a lot more after updating and putting in that logger. It's all in this text file here:

[error.txt](https://github.com/KevinJump/uSync/files/425343/error.txt)

**Comment by KevinJump** [comment]
OK,

It looks like you have a duplicate GUID inside the DB. 

the error is because Umbraco.Core.Services.ContentService.GetById(Guid key) is getting more than one content item for the same id : ( 

I'm not 100% sure how this occurs, usync looks things up by the key, so shouldn't then set the key to something that is already there - i will have to walk through the code. 

in terms of fixing it, we will need to find a way of changing the guid for the content you have (it might be a db thing) but again i will have a look, if i can reproduce it locally i might find a better fix.

Kevin

**Comment by LoganLehman** [comment]
@KevinJump,

I will look on my coworkers machine and my machine to compared GUIDs. Might take me a little bit, but it may help you look in the right direction.

Logan

**Comment by KevinJump** [comment]
Hi , i think

```
SELECT * FROM [umbracoNode] WHERE uniqueId in (
    SELECT [uniqueID]
        FROM [umbracoNode]
        GROUP BY [uniqueID] HAVING Count(*) > 1
    );  
```

will find any duplicates in the db

**Comment by kbbobiles** [comment]
@KevinJump 

Hi I'm Kenneth. Logan's coworker. I executed your SQL command, but resulted in 0 rows.

Kenneth

**Comment by LoganLehman** [comment]
@KevinJump,

I think my coworker is going to join in on the conversation, as I am unable to reproduce on my end (only on his machine). We received zero results from your query.

**Comment by KevinJump** [comment]
:disappointed:  - I'll have a look see if i can work anything else out

**Comment by LoganLehman** [comment]
Thanks @KevinJump. Sorry :(

**Comment by LoganLehman** [comment]
If it helps, the actual content node data I have is very test-like (doesn't have anything I would be worried giving out). If you want, I can zip up the data folder.

**Comment by KevinJump** [comment]
yeah feel free to drop me an email kevin@jumoo.co.uk

**Comment by LoganLehman** [comment]
@KevinJump - Sent. Let me know if you received it or not.

P.S. - This is the dataset of my coworker whom is having the issue. Made sure of that.

**Comment by KevinJump** [comment]
yep got it.

**Comment by KevinJump** [comment]
Hi

As far as i can tell, the target database has a duplicate entry in one of the tables where it's not meant to. (still don't know how it got there)

with any luck one of these queries below should return a row. that will be where it is broken. 

```
SELECT NodeId FROM [cmsContent] group by NodeId having count(*) > 1;
SELECT uniqueId FROM [umbracoNode] group by uniqueId having count(*) > 1;
SELECT ID FROM UMBRACONODE GROUP BY id having count(*) > 1;
SELECT NodeId from cmsDocument where newest = 'True' group by nodeId having count(*) > 1;
```

uSync doesn't actually go to the database directly (it does everything via the Umbraco API) - so i am trying to work through it somewhat. 

As far as i can tell you can end up with a duplicate node, (in cmsContent) or node (in umbracoNode) or have two active versions (in cmsDocument), if you do get something in one of these tables then we might be on to something.

_(the broken node is `Content\home\departments\finance\budget-research-purchasing\content.config` - the last log line is just before uSync does anything with it, then the call to find is what throws the error, because umbraco finds two of something)_

**Comment by LoganLehman** [comment]
@KevinJump,

@kbbobiles has left for the day, and will be back tomorrow (we are PST) - I don't have access to his machine, so we will run these queries tomorrow. Until then, thanks for all of the hard work on this. It is much appreciated. 

A food for thought, one of the changes to that node that occurred was a "move" in umbraco. I moved  "contract status report" node from "budget, purchasing & research" to "treasury management & accounting". That may lead in you in a direction hopefully.

Logan

**Comment by LoganLehman** [comment]
@KevinJump 

@kbbobiles ran the queries and found no results unfortunately. He reverted to a previous commit and it works fine, but the most recent commit of the uSync data seems to be causing the issue. We are still at a loss unfortunately.

**Comment by LoganLehman** [comment]
@KevinJump - Please also note that I am also using uSync Content Edition to sync content tree as well. Assumed you would know since the nodes were generated.

**Comment by KevinJump** [comment]
Hi yes - its part of the content sync that is causing the issue can you send me working and non working usync snapshots (i think i have the non working one) 
I might be able to see something &/or recreate the error between the two.

**Comment by LoganLehman** [comment]
@KevinJump 

Sure thing. I happened to just noticed as I was going through commits (based on when it "broke"), that the uSync/data/uSyncActions.config was deleted. Does this happen naturally? It happened when I did a full export. The content inside was this:

```
<?xml version="1.0" encoding="utf-8"?>
<ArrayOfSyncAction xmlns:xsd="http://www.w3.org/2001/XMLSchema"     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SyncAction>
    <TypeName>Umbraco.Core.Models.IDataTypeDefinition</TypeName>
    <Name>Insight: Excel Table</Name>
    <Key>611dd798-1296-4f48-93e7-974c86df9f87</Key>
    <Action>Delete</Action>
  </SyncAction>
</ArrayOfSyncAction>
```

**Comment by KevinJump** [comment]
Hi 

So i've come back to this with a clearer head. I think you have found the issue there with the uSyncAction.Config being deleted on a full export. 

the full export functionality was put in as a sort of 'start again' button - clearing everything down and giving you a clean install, but yes I can see if you already have synced things you might want to keep the action log around for deletes .

currently the export cleans the folder and then does a new export, I think maybe it's wise to provide an option to keep the action log on full export (and make that default) as getting the deletes out of sync can be a pain (as you have found out!) .
