### ISSUE TITLE
Error: An error has occurred. - The directory is not empty.

### ISSUE THREAD

**Issue by johnseto** [KevinJump/uSync3.0#82]
Just a heads up that this is occurring intermittently when click Full Export. Strangely the usyc/data directory does get cleared down and is empty when this message appears.

Sometimes a reboot sorts it or wait a while.

BTW: I have the latest release 3.2.2.740

**Comment by KevinJump** [comment]
thanks, 

I have seen this, if you have a file open (or maybe a command prompt) then i think the delete doesn't completely work and it throws the error. Need to put some better error control around the delete me thinks.

**Comment by KevinJump** [comment]
will be in 3.4
