### ISSUE TITLE
MultinodeTreePicker - Cannot search Listview children

### ISSUE THREAD

**Issue by ts-23** [KevinJump/uSync3.0#92]
Hi there, fantastic work on Usync. 

We seem to have encountered an inability to search for the children of a content node that is a listview when importing a document type containing multinode treepicker or content picker. Any ideas how to work around this would be greatly appreciated. 

Thank you in advance.

![image](https://cloud.githubusercontent.com/assets/13111256/19912164/bc7f3366-a0ec-11e6-8942-c137ebd223d8.png)

**Comment by KevinJump** [comment]
Hi 

does a search (in the backoffice in general) return the items in the list view? It might be that the Examine indexes have not been updated by the sync (but i am guessing a bit)

**Comment by KevinJump** [comment]
I am not sure this is a usync issue - if you can recreate i will re-open.
