### ISSUE TITLE
uSync Umbraco Forms definitions?

### ISSUE THREAD

**Issue by JoseMarcenaro** [KevinJump/uSync3.0#93]
Hi Kevin
Great job! uSync allows us to work as a team with separate databases in a seamless way. 

Q: Would it make sense to support sync'ing Umbraco Forms definitions (not the form entries)?
If you think so, I may take a shot at implementing something and submitting a Pull Request. 
Thanks,
Jose

**Comment by KevinJump** [comment]
yes! (although i haven't looked are the form definitions stored in the db, or are they already on the disk?) 

If you want to build it - I would start by looking at the ISyncHandlers.  https://github.com/KevinJump/uSync/tree/Dev-v7_4/Jumoo.uSync.BackOffice/Handlers 

It doesn't have to be implement directly in the core, if you look at [ContentEdition,](https://github.com/KevinJump/uSync/tree/Dev-v7_4/Jumoo.uSync.Content) you could implement the handlers in a separate dll. and uSync will just pull them in at runtime. 

_even if you put a core Serializer (https://github.com/KevinJump/uSync/tree/Dev-v7_4/Jumoo.uSync.Core/Serializers) you can in theory get them loaded in at runtime too. ) will be loaded dynamically at runtime if it implements `ISyncSerializer`_

**Comment by JoseMarcenaro** [comment]
Thanks for the clues!  I will start looking into that, and may contact you again to validate what I try to do before going much further. Thanks.

**Comment by JoseMarcenaro** [comment]
Kevin, your first question went straight to the point:
- **the form definitions are kept on disk**, not in the DB
- so **there is no need to use uSync** to transfer them - just copy the files

The complete procedure for transfering a form definition from one Umbraco installation to another is:
- Copy the form file "{guid}.json" located in  /App_Plugins/UmbracoForms/Data/forms to the target website
- Optionally, do the same with the workflow file located in /App_Plugins/UmbracoForms/Data/workflows and the prevalues in /App_Plugins/UmbracoForms/Data/prevaluesources
- On the target website, restart the app pool and refresh the Umbraco UI page to access the forms.

Of course, this does not transfer any form entries, which are kept in the DB (tables UFxxxxx).

Thanks for reviewing my (not so great) idea!  Please close the issue.
