### ISSUE TITLE
NuGet package missing package.manifest and JS files

### ISSUE THREAD

**Issue by harvzor** [KevinJump/uSync3.0#96]
After installing a fresh copy of Umbraco 7.5.4, followed by installing uSync.3.2.2.740 onto the website using NuGet, an error occurs in the uSync BackOffice dashboard section.

An error message is shown at the top: `Error: {{errorMsg}}`

Looking at the console in Firefox:

```
Error: Argument 'uSyncDashboardController' is not a function, got undefined
cb@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:17:79
xa@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:17:187
Jc/this.$get</<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:53:310
k/<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:44:274
n@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:7:72
k@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:44:139
e@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:40:139
y/<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:39:205
Od</<.compile/</</<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:158:14
u/j.success/<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:100:347
Uc/e/j.promise.then/i@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:79:432
Uc/e/j.promise.then/i@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:79:432
Uc/e/j.promise.then/i@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:79:432
Uc/e/j.promise.then/i@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:79:432
Uc/g/<.then/<@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:80:485
Xc/this.$get</e.prototype.$eval@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:92:268
Xc/this.$get</e.prototype.$digest@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:90:140
Xc/this.$get</e.prototype.$apply@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:92:429
j@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:101:78
r@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:104:449
dd/</w.onreadystatechange@http://landc.local/umbraco/lib/angular/1.1.5/angular.min.js?cdv=1:106:90
```

After looking in the App_Plugins/uSync folder, I saw that only CSS and HTML files were present, no package.manifest or JS files.

Comparing it to another uSync installation shows that the following are missing:

- package.manifest
- uSyncDashboardController.js
- uSyncDashboardService.js

Installing the previous version of uSync (3.2.1.740) included the aforementioned missing files.

**Comment by KevinJump** [comment]
Hummm, 

I'll have to look into that, because the package file looks like it has the js files in it. :( 

![image](https://cloud.githubusercontent.com/assets/431231/20479331/b126abe6-afd5-11e6-98d1-741c61133c86.png)

**Comment by harvzor** [comment]
@KevinJump It's been a while that this release has been the latest. Is it likely that it's only my system which has this fault? I feel like someone else would have picked it up otherwise.

**Comment by harvzor** [comment]
@KevinJump Actually, looking at another website I have in production, it has the latest version (3.2.2.740) installed and it has the files which are missing from my new installation. It must be something to do with this particular installation.

I'll see if I can look into the issue sometime.

**Comment by harvzor** [comment]
@KevinJump Thanks for the help here. Turned out it wasn't just your package getting the error as I found another package got pretty much the same problem too!

I cleared my NuGet cache with `nuget locals all -clear`, deleted any packages in my `packages` folder, and ran `nuget restore`. This time, all of the files were there.

Weird!
