### ISSUE TITLE
CORS issue when attempting to import

### ISSUE THREAD

**Issue by necoras** [KevinJump/uSync3.0#99]
We've recently come across a CORS issue with usync. I'm able to go into the uSync Back Office tab and navigate around. I can run the report of all the things which have changed. However, when I attempt to import I see "Error: undefined - undefined" in the error bar. Additionally there's a CORS error in the console:

![image](https://cloud.githubusercontent.com/assets/14185060/21055675/0d6a0bb6-bdf8-11e6-985e-ec1742bf5bfe.png)

I don't see any entries made in the umbraco log when I attempt to import changes. Any suggestions?

**Comment by KevinJump** [comment]
Hi does the domain in the blacked out section match the domain in the browser ? 

also i am suspicious of Flip script injected - but mainly because i don't know where that has come from :)

**Comment by necoras** [comment]
The blacked out domain is our domain, and yes it matches the domain in the browser. It has an exception granted to it via our web.config. That was necessary to allow umbraco to load all of its fonts and the like from our web server.

The flip script is a Chrome plugin that I have which allows me to "flip" page objects by increments of 90 degrees. It can't be related as this was originally reported to me by another dev from another PC. I duplicated it and uploaded my screenshot instead.

**Comment by KevinJump** [comment]
but that is the same domain as in the browser ? 

I think a CORS issue will only happen if the script being called isn't on the same domain as the page it is being called from ? so unless they are diffrent /or something funky is happening i am not sure how you are getting the error 

all of uSyncs dashboard elements are loaded from /app_plugins/usync on the server, and the calls go to /umbraco/usyncapi/ these "should" be the same site so no Cross Origin ?

**Comment by necoras** [comment]
Hrm. Interestingly the tab won't even load in Firefox unless I'm on the webserver itself. It must be a lot more picky than Chrome.

More confusingly (and infuriatingly), the import works fine with our Staging environment, but not our Dev. We must have some underlying environmental issue. I'll attack it from that angle. Thanks.

**Comment by KevinJump** [comment]
Cool, if you do find something - give us a shout, it will help others if they have the same issue.

**Comment by necoras** [comment]
Looks like it's an issue with a newly installed plugin. There's a package (Simple 301 I think) which is redirecting the incoming traffic from usync, which is requesting an http version of the page, to https and then back to http. That causes the initial CORS header to get lost. 

Since asp.net only allows for a single CORS whitelisted domain we have to specify either http or https for the umbraco back end, but not both. I've not figured out a way to make the umbraco back end play nicely with a certificate held at the load balancer level rather than the web server, so we end up with this issue. Tldr: Security is hard.
